name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Install packages
      run: |
        sudo dkp-pacman-key --recv-keys C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE --keyserver keyserver.ubuntu.com
        sudo dkp-pacman-key --lsign-key C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S --noconfirm --ask 4 wii-sdl2 wii-sdl2_image wii-sdl2_mixer

    - name: Checkout
      uses: actions/checkout@main

    - name: Build artifacts (Wii)
      run: make

    - name: Copy DOL
      run: cp ./LoopyMSE.dol ./hbc/boot.dol

    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: loopymse
        path: ./hbc/